//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIG.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Province
    {
        public Province()
        {
            this.Amphurs = new HashSet<Amphur>();
            this.Employees = new HashSet<Employee>();
            this.Addresses = new HashSet<Address>();
        }
    
        public string ID { get; set; }
        public string NAME_EN { get; set; }
        public string NAME_TH { get; set; }
    
        public virtual ICollection<Amphur> Amphurs { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
